### PR TITLE
Fix: Return correct calculation for presentation components with items (fixes #228)

### LINKED ISSUE #228: calculatePercentage issue for components with items
### Subject of the issue
In #221, the progress of presentation components with items are shown incrementally. That is, if 1 of 3 Narrative stages are completed, the PLP progress bar for the component will be 33% full.

This is breaking the "Complete page" option in [Dev Tools](https://github.com/cgkineo/adapt-devtools). Presentation components with items are not shown in the PLP drawer as being fully completed. However, it _does_ appear that the overall page is marked as completed.

### Your environment
* PLP 7.7.0
* Dev Tools 3.5.4

### Steps to reproduce
1. In the vanilla p101 build, go to Presentation Components
2. Open the Dev Tools drawer and select "Complete page"

### Result
Components with items (e.g. Narrative) are shown as partially complete.

PLP

### PR DESCRIPTION
**Pull request by swashbuck**
Fix #228 

### Fix
* Correctly calculates completion percentage when making presentation components with items complete.

### Testing
1. Install [Dev Tools](https://github.com/cgkineo/adapt-devtools/).
2. Visit a page that contains presentation components with items (e.g. Narrative, Accordion)
3. Click "Complete page" in Dev Tools
4. Alternatively, use similar [functionality](https://github.com/cgkineo/adapt-devtools/blob/ffd7369163c8e070060b78a08f23fa5c95144165/js/adapt-devtools.js#L285) to complete all components on the page.

### Expected result
Presentation components with items should show as 100% completed in the PLP drawer.

### CODE REVIEW

File: js/PageLevelProgressIndicatorView.js [hunk 1]
```diff
@@ -53,12 +53,14 @@ class PageLevelProgressIndicatorView extends Backbone.View {
 
   calculatePercentage() {
     const isPresentationComponentWithItems = (!this.model.isTypeGroup('question') && this.model instanceof ItemsComponentModel);
+    const isComplete = this.model.get('_isComplete');
```
Comment (oliverfoster) [inline js/PageLevelProgressIndicatorView.js:56]:
```suggestion
    const isComplete = this.model.get('_isComplete');
    if (isComplete) return 100;
```

File: js/PageLevelProgressIndicatorView.js [hunk 2]
```diff
@@ -53,12 +53,14 @@ class PageLevelProgressIndicatorView extends Backbone.View {
...
     if (isPresentationComponentWithItems) {
+      if (isComplete) return 100;
       const children = this.model.getChildren();
       const visited = children.filter(child => child.get('_isVisited'));
       return Math.round(visited.length / children.length * 100);
     }
-    return this.model.get('_isComplete') ? 100 : 0;
+    return isComplete ? 100 : 0;
```
Comment (oliverfoster) [inline js/PageLevelProgressIndicatorView.js:63]:
```suggestion
    return 0
```

File: js/PageLevelProgressIndicatorView.js [hunk 3]
```diff
@@ -53,12 +53,14 @@ class PageLevelProgressIndicatorView extends Backbone.View {
 
   calculatePercentage() {
     const isPresentationComponentWithItems = (!this.model.isTypeGroup('question') && this.model instanceof ItemsComponentModel);
+    const isComplete = this.model.get('_isComplete');
     if (isPresentationComponentWithItems) {
+      if (isComplete) return 100;
```
Comment (oliverfoster) [inline js/PageLevelProgressIndicatorView.js:58]:
```suggestion
```

**Review by oliverfoster — CHANGES_REQUESTED** [review]

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-allen-89 — APPROVED** [review]
👍
