### PR TITLE
Fix: Check for null value rather than length === 0 for empty collection (fixes #163)

### LINKED ISSUE #163: Pages won't load if no PLP components are on it
### Subject of the issue/enhancement/features
I've just created a fresh new course in the Framework and added a new page. The page had no components with PLP on it, even with the PLP JSON there but set to disabled and didn't load. I got this error

image

### Your environment
* version (AT/Framework) FW v5.24.8 
PLP v6.2.4

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
Fixes (#163)

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Check for null value rather than length === 0 for empty collection (fixes #163)

[//]: # (List appropriate steps for testing if needed)
### Testing
1. Create test course
2. Set all components on a page pageLevelProgress to false 
3. Load the page to ensure error is no longer visible and page is loading as expected. 

[//]: # (Mention any other dependencies)

### CODE REVIEW

**Review by oliverfoster — APPROVED** [review]

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by ethan-lp — APPROVED** [review]

File: js/adapt-contrib-pageLevelProgress.js [hunk 1]
```diff
@@ -136,7 +136,7 @@ class PageLevelProgress extends Backbone.Controller {
     if (viewType === 'course' && coursePLPConfig._showAtCourseLevel !== true) return;
 
     const collection = getPageLevelProgressItems(pageModel);
-    if (collection.length === 0) return;
+    if (collection === null) return;
```
Comment (eleanor-heath) [inline js/adapt-contrib-pageLevelProgress.js:139]:
```suggestion
    if (!collection) return;
```

Comment (joe-allen-89) [reply js/adapt-contrib-pageLevelProgress.js]: > 

Agreed, much nicer to read.
